### ISSUE TITLE
asdf list-all kconf does not return version numbers

### ISSUE THREAD

**Issue by bradym** [particledecay/asdf-kconf#1]
When I run `asdf list-all kconf` the output is not a list of versions. I've created a gist with the output I'm getting here: https://gist.github.com/bradym/9761522c2583fe07ecc599b7dbf7bb7c

This is happening both on MacOS and Ubuntu:

```
$ sw_vers
ProductName:	macOS
ProductVersion:	11.4
BuildVersion:	20F71

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

**Comment by particledecay** [comment]
Are you running that command with an auth token for GitHub? Do you know if this happens on a clean OS build? I can't reproduce this.

**Comment by bradym** [comment]
> Do you know if this happens on a clean OS build?
As a first step I tried on a different user account with no customized dotfiles and it worked fine.

Looks like this is an issue with my .curlrc. I had defined a user-agent string at some point, when I remove that it works fine. Sorry for the noise.
